import { describe, it, expect } from 'vitest'
import * as path from 'path'
import * as os from 'os'
import { parseTf } from './parse'
import { evaluate } from '../engine/evaluate'
import { rule } from '../spec/rule'
import { AwsResource, Port } from '../vocabulary'

// #22: a perf benchmark on a synthetic large repo (100 root files × 10 SGs =
// 1000 direct resources + 100 module calls to a 2-resource module = 200
// followed = 1200 resources). Asserts parse+evaluate completes in a reasonable
// time so a regression (e.g. an accidental O(n²)) is caught. NOT a hard SLA —
// the threshold is generous (10s) to avoid CI flakiness; the printout shows
// the real number for visibility.
describe('parseTf + evaluate — performance on a large synthetic repo (#22)', () => {
  it('handles 1200 resources (100 root files + 100 module calls) in < 10s', async () => {
    const dir = path.join(
      os.tmpdir(),
      '..',
      '..',
      'var',
      'folders',
      'vw',
      '7zjgylqs2hl7ntnk6rvm31600000gn',
      'T',
      'opencode',
      'bench',
    )
    // Fallback: the opencode temp dir (where bench/gen.js writes).
    const alt =
      '/var/folders/vw/7zjgylqs2hl7ntnk6rvm31600000gn/T/opencode/bench'
    // The fixture is generated by bench/gen.js; if absent, skip (this test is
    // informational, not a correctness gate).
    const fs = await import('fs')
    const benchDir = fs.existsSync(path.join(alt, 'main.tf')) ? alt : dir
    if (!fs.existsSync(path.join(benchDir, 'main.tf'))) {
      console.log('(bench fixture absent — skipping)')
      return
    }

    const r = rule()
      .resource(AwsResource.SecurityGroup)
      .denyIngress(Port.SSH)
      .message('no ssh')
      .validate(0)
    const ruleVal = r.ok ? r.value : null
    expect(ruleVal).not.toBeNull()

    const t0 = Date.now()
    const p = await parseTf(benchDir, benchDir)
    const t1 = Date.now()
    expect(p.ok).toBe(true)
    if (!p.ok) return
    const rep = evaluate(
      [ruleVal!],
      p.value.resources,
      p.value.outputs,
      p.value.bindings,
      p.value.settings,
      p.value.moduleCalls,
    )
    const t2 = Date.now()
    const total = t2 - t0
    console.log(
      `#22 perf: parseTf ${t1 - t0}ms, evaluate ${t2 - t1}ms, TOTAL ${total}ms | ` +
        `resources=${p.value.resources.length} moduleCalls=${p.value.moduleCalls.length} ` +
        `violations=${rep.violations.length} passed=${rep.passed}`,
    )
    // Generous threshold — catches an accidental quadratic blowup, not a 5% wobble.
    expect(total).toBeLessThan(10_000)
  })
}, 30_000)
