/** Public DSL surface — what `.zen/spec.ts` imports. */
export { rule, RuleBuilder } from './spec/rule'
export {
  AwsResource,
  Port,
  Cidr,
  Effect,
  Tag,
  AwsAttribute,
  Acl,
  Environment,
  Approver,
  HttpTokens,
  EksLogType,
  TlsPolicy,
  Protocol,
  Block,
  Wildcard,
  ApiGatewayAuthorization,
  AzureResource,
  AzureAttribute,
  StorageTlsVersion,
  SqlTlsVersion,
  BuiltInRole,
  NetworkDefaultAction,
  GcpResource,
  GcpAttribute,
  PublicAccessPreventionMode,
  IamMember,
  PrimitiveRole,
  OauthScope,
  SqlSslMode,
} from './vocabulary'
