/**
 * Azure (azurerm) vocabulary. Kept in its own provider module — not merged
 * into the AWS `AwsResource`/`AwsAttribute` enums — so each cloud's `spec.ts`
 * reads in its own idiom and the enums stay small ("Prose as Code"). The
 * shared `AnyResource`/`AnyAttribute` unions (in ./index) let the
 * cloud-neutral engine accept every provider's vocabulary.
 */

export enum AzureResource {
  NetworkSecurityGroup = 'azurerm_network_security_group',
  // Standalone NSG rule (the decomposed form of an inline `security_rule`).
  NetworkSecurityRule = 'azurerm_network_security_rule',
  StorageAccount = 'azurerm_storage_account',
  MssqlServer = 'azurerm_mssql_server',
  KeyVault = 'azurerm_key_vault',
  KubernetesCluster = 'azurerm_kubernetes_cluster',
  LinuxWebApp = 'azurerm_linux_web_app',
  WindowsWebApp = 'azurerm_windows_web_app',
  PostgresqlServer = 'azurerm_postgresql_server',
  MysqlServer = 'azurerm_mysql_server',
  ContainerRegistry = 'azurerm_container_registry',
  CosmosdbAccount = 'azurerm_cosmosdb_account',
  RoleDefinition = 'azurerm_role_definition',
  RoleAssignment = 'azurerm_role_assignment',
  ManagedDisk = 'azurerm_managed_disk',
  MonitorDiagnosticSetting = 'azurerm_monitor_diagnostic_setting',
  ApiManagement = 'azurerm_api_management',
  // Azure Functions (serverless). v4 preferrred `linux/windows_function_app`;
  // `function_app` is the legacy v3 combined resource. `https_only`,
  // `public_network_access_enabled`, and the `identity {}` block are shared
  // with Linux/Windows web apps; `site_config.minimum_tls_version` is the
  // function-app TLS floor.
  LinuxFunctionApp = 'azurerm_linux_function_app',
  WindowsFunctionApp = 'azurerm_windows_function_app',
  FunctionApp = 'azurerm_function_app',

  // ── ROADMAP item 2: Azure supporting-resource vocabulary ──────────────
  // Recognized-but-not-yet-rule-bearing. Removes `ungoverned` noise on
  // real azurerm module repos. Add-only; no engine work unless a resource
  // has structure normalize doesn't already flatten generically.
  // Networking — VNet / subnets / NIC / LB / DNS
  VirtualNetwork = 'azurerm_virtual_network',
  Subnet = 'azurerm_subnet',
  NetworkInterface = 'azurerm_network_interface',
  PublicIp = 'azurerm_public_ip',
  PublicIpPrefix = 'azurerm_public_ip_prefix',
  ApplicationSecurityGroup = 'azurerm_application_security_group',
  Route = 'azurerm_route',
  RouteTable = 'azurerm_route_table',
  ApplicationGateway = 'azurerm_application_gateway',
  ApplicationGatewayWafPolicy = 'azurerm_web_application_firewall_policy',
  LoadBalancer = 'azurerm_lb',
  LoadBalancerBackendAddressPool = 'azurerm_lb_backend_address_pool',
  LoadBalancerRule = 'azurerm_lb_rule',
  LoadBalancerOutboundRule = 'azurerm_lb_outbound_rule',
  LoadBalancerProbe = 'azurerm_lb_probe',
  LoadBalancerNatRule = 'azurerm_lb_nat_rule',
  LoadBalancerNatPool = 'azurerm_lb_nat_pool',
  TrafficManagerProfile = 'azurerm_traffic_manager_profile',
  TrafficManagerEndpoint = 'azurerm_traffic_manager_endpoint',
  PrivateDnsZone = 'azurerm_private_dns_zone',
  PrivateDnsZoneVirtualNetworkLink = 'azurerm_private_dns_zone_virtual_network_link',
  PrivateEndpoint = 'azurerm_private_endpoint',
  PrivateLinkService = 'azurerm_private_link_service',
  DnsZone = 'azurerm_dns_zone',
  DnsARecord = 'azurerm_dns_a_record',
  DnsAaaaRecord = 'azurerm_dns_aaaa_record',
  DnsCnameRecord = 'azurerm_dns_cname_record',
  DnsMxRecord = 'azurerm_dns_mx_record',
  DnsPtrRecord = 'azurerm_dns_ptr_record',
  DnsTxtRecord = 'azurerm_dns_txt_record',
  DnsSrvRecord = 'azurerm_dns_srv_record',
  DnsNsRecord = 'azurerm_dns_ns_record',
  DnsCaaRecord = 'azurerm_dns_caa_record',
  Frontdoor = 'azurerm_frontdoor',
  FrontdoorCustomHttpsConfiguration = 'azurerm_frontdoor_custom_https_configuration',
  FrontdoorFirewallPolicy = 'azurerm_frontdoor_firewall_policy',
  FrontdoorRulesEngine = 'azurerm_frontdoor_rules_engine',
  CdnProfile = 'azurerm_cdn_profile',
  CdnEndpoint = 'azurerm_cdn_endpoint',
  CdnFrontdoorEndpoint = 'azurerm_cdn_frontdoor_endpoint',
  CdnFrontdoorOrigin = 'azurerm_cdn_frontdoor_origin',
  CdnFrontdoorOriginGroup = 'azurerm_cdn_frontdoor_origin_group',
  CdnFrontdoorRule = 'azurerm_cdn_frontdoor_rule',
  CdnFrontdoorRuleSet = 'azurerm_cdn_frontdoor_rule_set',
  CdnFrontdoorSecurityPolicy = 'azurerm_cdn_frontdoor_security_policy',
  CdnFrontdoorCustomDomain = 'azurerm_cdn_frontdoor_custom_domain',
  CdnFrontdoorRoute = 'azurerm_cdn_frontdoor_route',
  CdnFrontdoorSecret = 'azurerm_cdn_frontdoor_secret',
  CdnFrontdoorPolicy = 'azurerm_cdn_frontdoor_firewall_policy',
  // Compute / VM / VMSS
  LinuxVirtualMachine = 'azurerm_linux_virtual_machine',
  WindowsVirtualMachine = 'azurerm_windows_virtual_machine',
  LinuxVirtualMachineScaleSet = 'azurerm_linux_virtual_machine_scale_set',
  WindowsVirtualMachineScaleSet = 'azurerm_windows_virtual_machine_scale_set',
  VirtualMachine = 'azurerm_virtual_machine',
  VirtualMachineExtension = 'azurerm_virtual_machine_extension',
  VirtualMachineScaleSet = 'azurerm_virtual_machine_scale_set',
  VirtualMachineScaleSetExtension = 'azurerm_virtual_machine_scale_set_extension',
  AvailabilitySet = 'azurerm_availability_set',
  ProximityPlacementGroup = 'azurerm_proximity_placement_group',
  DedicatedHost = 'azurerm_dedicated_host',
  DedicatedHostGroup = 'azurerm_dedicated_host_group',
  CapacityReservationGroup = 'azurerm_capacity_reservation_group',
  CapacityReservation = 'azurerm_capacity_reservation',
  ImageBuilderTemplate = 'azurerm_image_builder_template',
  SharedImage = 'azurerm_shared_image',
  SharedImageGallery = 'azurerm_shared_image_gallery',
  // Storage
  StorageAccountNetworkAcls = 'azurerm_storage_account_network_rules',
  StorageContainer = 'azurerm_storage_container',
  StorageBlob = 'azurerm_storage_blob',
  StorageShare = 'azurerm_storage_share',
  StorageQueue = 'azurerm_storage_queue',
  StorageTable = 'azurerm_storage_table',
  StorageDataLakeGen2Filesystem = 'azurerm_storage_data_lake_gen2_filesystem',
  StorageSync = 'azurerm_storage_sync',
  StorageSyncGroup = 'azurerm_storage_sync_group',
  StorageSyncCloudEndpoint = 'azurerm_storage_sync_cloud_endpoint',
  StorageMover = 'azurerm_storage_mover',
  NetappAccount = 'azurerm_netapp_account',
  NetappPool = 'azurerm_netapp_pool',
  NetappVolume = 'azurerm_netapp_volume',
  NetappSnapshotPolicy = 'azurerm_netapp_snapshot_policy',
  // Database / data
  MssqlDatabase = 'azurerm_mssql_database',
  MssqlServerSecurityAlertPolicy = 'azurerm_mssql_server_security_alert_policy',
  MssqlServerVulnerabilityAssessment = 'azurerm_mssql_server_vulnerability_assessment',
  MssqlVirtualMachine = 'azurerm_mssql_virtual_machine',
  PostgresqlFlexibleServer = 'azurerm_postgresql_flexible_server',
  PostgresqlDatabase = 'azurerm_postgresql_database',
  PostgresqlConfiguration = 'azurerm_postgresql_configuration',
  PostgresqlFirewallRule = 'azurerm_postgresql_firewall_rule',
  PostgresqlVirtualNetworkRule = 'azurerm_postgresql_virtual_network_rule',
  MysqlFlexibleServer = 'azurerm_mysql_flexible_server',
  MysqlDatabase = 'azurerm_mysql_database',
  MysqlFirewallRule = 'azurerm_mysql_firewall_rule',
  MysqlVirtualNetworkRule = 'azurerm_mysql_virtual_network_rule',
  MariadbServer = 'azurerm_mariadb_server',
  MariadbDatabase = 'azurerm_mariadb_database',
  MariadbFirewallRule = 'azurerm_mariadb_firewall_rule',
  CosmosdbSqlDatabase = 'azurerm_cosmosdb_sql_database',
  CosmosdbMongoDatabase = 'azurerm_cosmosdb_mongo_database',
  CosmosdbCassandraKeyspace = 'azurerm_cosmosdb_cassandra_keyspace',
  CosmosdbGremlinDatabase = 'azurerm_cosmosdb_gremlin_database',
  CosmosdbTable = 'azurerm_cosmosdb_table',
  CosmosdbNotebookWorkspace = 'azurerm_cosmosdb_notebook_workspace',
  CosmosdbSqlContainer = 'azurerm_cosmosdb_sql_container',
  CosmosdbMongoCollection = 'azurerm_cosmosdb_mongo_collection',
  CosmosdbCassandraTable = 'azurerm_cosmosdb_cassandra_table',
  CosmosdbGremlinGraph = 'azurerm_cosmosdb_gremlin_graph',
  CosmosdbSqlStoredProcedure = 'azurerm_cosmosdb_sql_stored_procedure',
  CosmosdbSqlTrigger = 'azurerm_cosmosdb_sql_trigger',
  CosmosdbSqlUserDefinedFunction = 'azurerm_cosmosdb_sql_user_defined_function',
  DataFactory = 'azurerm_data_factory',
  DataFactoryPipeline = 'azurerm_data_factory_pipeline',
  DataFactoryDataset = 'azurerm_data_factory_dataset',
  DataFactoryLinkedService = 'azurerm_data_factory_linked_service',
  DataFactoryIntegrationRuntime = 'azurerm_data_factory_integration_runtime',
  DataFactoryTrigger = 'azurerm_data_factory_trigger',
  DatabricksWorkspace = 'azurerm_databricks_workspace',
  DatabricksWorkspaceEncryption = 'azurerm_databricks_workspace_customer_managed_key',
  SynapseWorkspace = 'azurerm_synapse_workspace',
  SynapseSparkPool = 'azurerm_synapse_spark_pool',
  SynapseSqlPool = 'azurerm_synapse_sql_pool',
  DataLakeStore = 'azurerm_data_lake_store',
  AnalysisServicesServer = 'azurerm_analysis_services_server',
  // Containers / AKS additions
  KubernetesClusterNodePool = 'azurerm_kubernetes_cluster_node_pool',
  ContainerApp = 'azurerm_container_app',
  ContainerAppEnvironment = 'azurerm_container_app_environment',
  ContainerGroup = 'azurerm_container_group',
  ServiceFabricCluster = 'azurerm_service_fabric_cluster',
  ServiceFabricManagedCluster = 'azurerm_service_fabric_managed_cluster',
  // IAM / Identity
  UserAssignedIdentity = 'azurerm_user_assigned_identity',
  ApplicationInsights = 'azurerm_application_insights',
  ApplicationInsightsWebTest = 'azurerm_application_insights_web_test',
  ApplicationInsightsAnalyticsItem = 'azurerm_application_insights_analytics_item',
  LogAnalyticsWorkspace = 'azurerm_log_analytics_workspace',
  LogAnalyticsSolution = 'azurerm_log_analytics_solution',
  LogAnalyticsLinkedService = 'azurerm_log_analytics_linked_service',
  LogAnalyticsDataExportRule = 'azurerm_log_analytics_data_export_rule',
  LogAnalyticsLinkedStorageAccount = 'azurerm_log_analytics_linked_storage_account',
  LogAnalyticsQueryPack = 'azurerm_log_analytics_query_pack',
  LogAnalyticsQueryPackQuery = 'azurerm_log_analytics_query_pack_query',
  AutomationAccount = 'azurerm_automation_account',
  AutomationRunbook = 'azurerm_automation_runbook',
  AutomationSchedule = 'azurerm_automation_schedule',
  AutomationVariable = 'azurerm_automation_variable',
  AutomationCredential = 'azurerm_automation_credential',
  AutomationCertificate = 'azurerm_automation_certificate',
  AutomationConnection = 'azurerm_automation_connection',
  AutomationModule = 'azurerm_automation_module',
  AutomationDscConfiguration = 'azurerm_automation_dsc_configuration',
  AutomationWebhook = 'azurerm_automation_webhook',
  // Key Vault extras
  KeyVaultCertificate = 'azurerm_key_vault_certificate',
  KeyVaultKey = 'azurerm_key_vault_key',
  KeyVaultSecret = 'azurerm_key_vault_secret',
  KeyVaultAccessPolicy = 'azurerm_key_vault_access_policy',
  KeyVaultCertificateData = 'azurerm_key_vault_certificate_data',
  KeyVaultManagedHardwareSecurityModule = 'azurerm_key_vault_managed_hsm',
  // Security / monitoring
  LogProfile = 'azurerm_monitor_log_profile',
  ActivityLogAlert = 'azurerm_monitor_activity_log_alert',
  MetricAlert = 'azurerm_metric_alert',
  ScheduledQueryRuleAlert = 'azurerm_monitor_scheduled_query_rules_alert',
  ScheduledQueryRuleLog = 'azurerm_monitor_scheduled_query_rules_log',
  MonitorActionGroup = 'azurerm_monitor_action_group',
  MonitorSmartDetectorAlertRule = 'azurerm_monitor_smart_detector_alert_rule',
  MonitorAutoscaleSetting = 'azurerm_monitor_autoscale_setting',
  AdvancedThreatProtection = 'azurerm_advanced_threat_protection',
  SecurityCenterContact = 'azurerm_security_center_contact',
  SecurityCenterWorkspace = 'azurerm_security_center_workspace',
  SecurityCenterSetting = 'azurerm_security_center_setting',
  SecurityCenterSubscriptionPricing = 'azurerm_security_center_subscription_pricing',
  SentinelAlertRule = 'azurerm_sentinel_alert_rule',
  SentinelAlertRuleTemplate = 'azurerm_sentinel_alert_rule_template',
  SentinelDataConnector = 'azurerm_sentinel_data_connector',
  SentinelWatchlist = 'azurerm_sentinel_watchlist',
  // Backup / recovery
  BackupPolicyVm = 'azurerm_backup_policy_vm',
  BackupPolicyVmWorkload = 'azurerm_backup_policy_vm_workload',
  BackupPolicyFileShare = 'azurerm_backup_policy_file_share',
  BackupContainerStorageAccount = 'azurerm_backup_container_storage_account',
  BackupProtectedFileShare = 'azurerm_backup_protected_file_share',
  BackupProtectedVm = 'azurerm_backup_protected_vm',
  RecoveryServicesVault = 'azurerm_recovery_services_vault',
  SiteRecoveryReplicatedVm = 'azurerm_site_recovery_replicated_vm',
  SiteRecoveryFabric = 'azurerm_site_recovery_fabric',
  SiteRecoveryProtectionContainer = 'azurerm_site_recovery_protection_container',
  SiteRecoveryNetworkMapping = 'azurerm_site_recovery_network_mapping',
  SiteRecoveryReplicationRecoveryPlan = 'azurerm_site_recovery_replication_recovery_plan',
  // Event GRID / Service Bus / Event Hub / IoT Hub / SignalR
  EventgridTopic = 'azurerm_eventgrid_topic',
  EventgridDomain = 'azurerm_eventgrid_domain',
  EventgridEventSubscription = 'azurerm_eventgrid_event_subscription',
  EventgridSystemTopic = 'azurerm_eventgrid_system_topic',
  ServicebusQueue = 'azurerm_servicebus_queue',
  ServicebusTopic = 'azurerm_servicebus_topic',
  ServicebusSubscription = 'azurerm_servicebus_subscription',
  ServicebusNamespace = 'azurerm_servicebus_namespace',
  ServicebusNamespaceAuthorizationRule = 'azurerm_servicebus_namespace_authorization_rule',
  ServicebusQueueAuthorizationRule = 'azurerm_servicebus_queue_authorization_rule',
  ServicebusTopicAuthorizationRule = 'azurerm_servicebus_topic_authorization_rule',
  Eventhub = 'azurerm_eventhub',
  EventhubConsumerGroup = 'azurerm_eventhub_consumer_group',
  EventhubAuthorizationRule = 'azurerm_eventhub_authorization_rule',
  EventhubNamespace = 'azurerm_eventhub_namespace',
  EventhubCluster = 'azurerm_eventhub_cluster',
  Iothub = 'azurerm_iothub',
  IothubConsumerGroup = 'azurerm_iothub_consumer_group',
  IothubDps = 'azurerm_iothub_dps',
  IothubDpsCertificate = 'azurerm_iothub_dps_certificate',
  Signalr = 'azurerm_signalr_service',
  SignalrCustomCert = 'azurerm_signalr_service_custom_cert',
  SignalrSharedPrivateLinkResource = 'azurerm_signalr_service_shared_private_link_resource',
  // API extras
  ApiManagementApi = 'azurerm_api_management_api',
  ApiManagementApiOperation = 'azurerm_api_management_api_operation',
  ApiManagementBackend = 'azurerm_api_management_backend',
  ApiManagementLogger = 'azurerm_api_management_logger',
  ApiManagementDiagnostic = 'azurerm_api_management_diagnostic',
  ApiManagementPolicy = 'azurerm_api_management_policy',
  ApiManagementProduct = 'azurerm_api_management_product',
  ApiManagementSubscription = 'azurerm_api_management_subscription',
  ApiManagementUser = 'azurerm_api_management_user',
  ApiManagementGroup = 'azurerm_api_management_group',
  ApiManagementCertificate = 'azurerm_api_management_certificate',
  ApiManagementNamedValue = 'azurerm_api_management_named_value',
  ApiManagementAuthorizationServer = 'azurerm_api_management_authorization_server',
  ApiManagementOpenIdConnectProvider = 'azurerm_api_management_openid_connect_provider',
  // Functions / app service extras
  AppServicePlan = 'azurerm_app_service_plan',
  ServicePlan = 'azurerm_service_plan',
  AppService = 'azurerm_app_service',
  AppServiceSlot = 'azurerm_app_service_slot',
  AppServiceSourceControl = 'azurerm_app_service_source_control',
  AppServiceCustomHostnameBinding = 'azurerm_app_service_custom_hostname_binding',
  AppServiceManagedCertificate = 'azurerm_app_service_managed_certificate',
  AppServiceCertificate = 'azurerm_app_service_certificate',
  AppServiceCertificateOrder = 'azurerm_app_service_certificate_order',
  AppServiceHybridConnection = 'azurerm_app_service_hybrid_connection',
  StaticWebApp = 'azurerm_static_web_app',
  // Resource groups / locks / tags / policy
  ResourceGroup = 'azurerm_resource_group',
  ManagementLock = 'azurerm_management_lock',
  PolicyDefinition = 'azurerm_policy_definition',
  PolicyAssignment = 'azurerm_policy_assignment',
  PolicySetDefinition = 'azurerm_policy_set_definition',
  PolicyExemption = 'azurerm_policy_exemption',
  Blueprint = 'azurerm_blueprint_assignment',
  // Batch / ML / Bot / Maps / Cognitive
  BatchAccount = 'azurerm_batch_account',
  BatchPool = 'azurerm_batch_pool',
  MachineLearningWorkspace = 'azurerm_machine_learning_workspace',
  MachineLearningComputeCluster = 'azurerm_machine_learning_compute_cluster',
  MachineLearningComputeInstance = 'azurerm_machine_learning_compute_instance',
  MachineLearningSynapseSpark = 'azurerm_machine_learning_synapse_spark',
  CognitiveAccount = 'azurerm_cognitive_account',
  BotChannelsRegistration = 'azurerm_bot_channels_registration',
  BotWebApp = 'azurerm_bot_web_app',
  BotConnection = 'azurerm_bot_connection',
  MapsAccount = 'azurerm_maps_account',
  // CDN / frontdoor extras covered above
  // Active Directory domain services
  Aadds = 'azurerm_active_directory_domain_service',
  AaddsReplicaSet = 'azurerm_active_directory_domain_service_replica_set',
  HealthcareWorkspace = 'azurerm_healthcare_workspace',
  HealthLake = 'azurerm_healthcare_service',
  LogicAppWorkflow = 'azurerm_logic_app_workflow',
  LogicAppActionCustom = 'azurerm_logic_app_action_custom',
  LogicAppTriggerCustom = 'azurerm_logic_app_trigger_custom',
  // Container Registry extras
  ContainerRegistryAgentPool = 'azurerm_container_registry_agent_pool',
  ContainerRegistryTask = 'azurerm_container_registry_task',
  ContainerRegistryWebhook = 'azurerm_container_registry_webhook',
  ContainerRegistryScopeMap = 'azurerm_container_registry_scope_map',
  ContainerRegistryToken = 'azurerm_container_registry_token',
  // Devtest Labs
  DevtestLab = 'azurerm_dev_test_lab',
  DevtestVirtualMachine = 'azurerm_dev_test_virtual_machine',
  DevtestCustomImage = 'azurerm_dev_test_custom_image',
  DevtestPolicy = 'azurerm_dev_test_policy',
  DevtestSchedule = 'azurerm_dev_test_schedule',
  DevtestVirtualNetwork = 'azurerm_dev_test_virtual_network',
  // Network Watcher / Traffic Manager / Bastion
  NetworkWatcher = 'azurerm_network_watcher',
  NetworkWatcherFlowLog = 'azurerm_network_watcher_flow_log',
  BastionHost = 'azurerm_bastion_host',
  LocalNetworkGateway = 'azurerm_local_network_gateway',
  VirtualNetworkGateway = 'azurerm_virtual_network_gateway',
  VirtualNetworkGatewayConnection = 'azurerm_virtual_network_gateway_connection',
  // Data Bricks / Stream Analytics / Functions extras
  StreamAnalyticsJob = 'azurerm_stream_analytics_job',
  StreamAnalyticsInput = 'azurerm_stream_analytics_input',
  StreamAnalyticsOutput = 'azurerm_stream_analytics_output',
  StreamAnalyticsFunction = 'azurerm_stream_analytics_function',
  // Cache / Redis / HDInsight
  RedisCache = 'azurerm_redis_cache',
  RedisEnterpriseCluster = 'azurerm_redis_enterprise_cluster',
  RedisEnterpriseDatabase = 'azurerm_redis_enterprise_database',
  RedisFirewallRule = 'azurerm_redis_firewall_rule',
  RedisLinkedServer = 'azurerm_redis_linked_server',
  HdinsightHadoopCluster = 'azurerm_hdinsight_hadoop_cluster',
  HdinsightHbaseCluster = 'azurerm_hdinsight_hbase_cluster',
  HdinsightKafkaCluster = 'azurerm_hdinsight_kafka_cluster',
  HdinsightInteractiveQueryCluster = 'azurerm_hdinsight_interactive_query_cluster',
  HdinsightMlServicesCluster = 'azurerm_hdinsight_ml_services_cluster',
  HdinsightRserverCluster = 'azurerm_hdinsight_rserver_cluster',
  HdinsightSparkCluster = 'azurerm_hdinsight_spark_cluster',
  HdinsightStormCluster = 'azurerm_hdinsight_storm_cluster',
  // Communication / Purview / Digital Twins
  CommunicationService = 'azurerm_communication_service',
  CommunicationSms = 'azurerm_sms_communication_service',
  PurviewAccount = 'azurerm_purview_account',
  DigitalTwinsInstance = 'azurerm_digital_twins_instance',
  // HSM extras
  KeyVaultManagedHsmRoleAssignment = 'azurerm_key_vault_managed_hsm_role_assignment',
  KeyVaultManagedHsmRoleDefinition = 'azurerm_key_vault_managed_hsm_role_definition',
}

export enum AzureAttribute {
  // Storage account
  AllowNestedItemsToBePublic = 'allow_nested_items_to_be_public',
  MinTlsVersion = 'min_tls_version',
  PublicNetworkAccessEnabled = 'public_network_access_enabled',
  // MSSQL server
  MinimumTlsVersion = 'minimum_tls_version',
  AdministratorLoginPassword = 'administrator_login_password',
  // Key Vault
  PurgeProtectionEnabled = 'purge_protection_enabled',
  // AKS
  PrivateClusterEnabled = 'private_cluster_enabled',
  LocalAccountDisabled = 'local_account_disabled',
  // App Service (Linux/Windows web app)
  HttpsOnly = 'https_only',
  // PostgreSQL / MySQL single server
  SslEnforcementEnabled = 'ssl_enforcement_enabled',
  // Container Registry
  AdminEnabled = 'admin_enabled',
  // RBAC (role_definition permissions block flattens to a list)
  RoleActions = 'permissions.actions',
  RoleDefinitionName = 'role_definition_name',
  // Network default-deny (nested) + CMK + diagnostic association
  NetworkRulesDefaultAction = 'network_rules.default_action',
  NetworkAclsDefaultAction = 'network_acls.default_action',
  DiskEncryptionSetId = 'disk_encryption_set_id',
  TargetResourceId = 'target_resource_id',
  // API Management legacy protocol toggles (nested under `security`)
  EnableFrontendTls10 = 'security.enable_frontend_tls10',
  EnableFrontendTls11 = 'security.enable_frontend_tls11',
  EnableBackendSsl30 = 'security.enable_backend_ssl30',
  // Azure Functions — site_config TLS floor (nested block, dotted).
  SiteConfigMinTlsVersion = 'site_config.minimum_tls_version',
}

// Built-in Azure roles that grant broad control (for denyValue on an
// azurerm_role_assignment).
export enum BuiltInRole {
  Owner = 'Owner',
  Contributor = 'Contributor',
}

// The secure default_action for storage/key-vault network rules.
export enum NetworkDefaultAction {
  Deny = 'Deny',
}

// Storage account TLS floor (note the storage-specific `TLS1_2` spelling).
export enum StorageTlsVersion {
  Tls12 = 'TLS1_2',
}

// MSSQL server TLS versions (a bare numeric string, unlike storage).
export enum SqlTlsVersion {
  V10 = '1.0',
  V11 = '1.1',
  V12 = '1.2',
}
